# Generated by Django 3.0.5 on 2020-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plant_last_irrigation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_irrigation_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date'),
        ),
    ]
