# Generated by Django 3.0.5 on 2020-05-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_plant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('wait', 'Wait'), ('irrigate', 'Irrigate')], default='wait', max_length=10),
        ),
    ]
