# Generated by Django 3.0.5 on 2020-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20200510_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='irrigation_count',
            field=models.IntegerField(default=0),
        ),
    ]
