# Generated by Django 3.0.5 on 2020-06-03 20:53

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20200531_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='city',
            field=models.CharField(default='Izmir', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='irrigation_type',
            field=models.CharField(choices=[('surface', 'Surface'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('subsurface', 'Subsurface')], default='drip', max_length=10),
        ),
        migrations.AddField(
            model_name='plant',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
