# Generated by Django 3.0.5 on 2020-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20200603_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='irrigation_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plant',
            name='machine_learning',
            field=models.BooleanField(default=True),
        ),
    ]
