# Generated by Django 3.0.5 on 2020-06-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20200604_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='max_manual_irrigation_for_machine_learning',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='plant',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
