# Generated by Django 3.0.5 on 2020-04-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_temperature', models.FloatField(blank=True, verbose_name='Air Temperature')),
                ('air_humidity', models.FloatField(blank=True, verbose_name='Air Humidity')),
                ('soil_moisture', models.IntegerField(blank=True, verbose_name='Soil Moisture')),
                ('date', models.DateTimeField(blank=True, verbose_name='Date')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='plant.Plant', verbose_name='Plant')),
            ],
        ),
    ]
