# Generated by Django 3.0.5 on 2020-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='data',
            name='epoch',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Epoch Time'),
            preserve_default=False,
        ),
    ]
