# Generated by Django 3.0.5 on 2020-05-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Data Summary',
                'verbose_name_plural': 'Data Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.data',),
        ),
    ]
