# Generated by Django 3.0.5 on 2020-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datasummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='irrigation',
            field=models.BooleanField(default=False),
        ),
    ]
